### ISSUE TITLE
ohmyzsh  aws plugin support

### ISSUE THREAD

**Issue by chrowe** [synfinatic/aws-sso-cli#1078]
**Is your feature request related to a problem? Please describe.**
I use ohmyzsh and I really like the way the active aws profile shows up when running aws commands. When using `aws-sso-profile` the active profile is not showing up.

**Describe the solution you'd like**
Integrate with https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/aws or create something similar

**Comment by synfinatic** [comment]
This is no doubt because `aws-sso-profile` does not export `AWS_PROFILE` which is what is ohmyzsh is using.   I can't export that variable because then it you get inconsistent and broken behaviors with the AWS SDK.  It's so broken that if `AWS_PROFILE` is set, then `aws-sso-profile` will refuse to run.

Instead, you'll have to teach ohmyzsh about `AWS_SSO_PROFILE` which is the equivalent variable when using `aws-sso-profile`.  Basically, I don't see a path forward for `aws-sso` to create the behavior you desire.  Your best bet IMHO is to write the necessary plugin and contribute that to the ohmyzsh project.

Alternatively, if you'd like to use the existing ohmyzsh plugin, you can use the [config-profiles](https://synfinatic.github.io/aws-sso-cli/v1.17.0/commands/#config-profiles) command (note the name of this command changes in v2.x) and then just `export AWS_PROFILE=xxxx` normally.   Not sure if ohmyzsh or similar does auto-completion for that though.
