### ISSUE TITLE
Multiple tabs of authorization

### ISSUE THREAD

**Issue by monwolf** [synfinatic/aws-sso-cli#110]
Hey, 

I'm using your software to setup aws-sso and get cretentials to log into eks. The software I'm using tries to refresh the credentials once they have been expired.
I left my computer powered on with this software running and when I opened signed in again  I saw this in my browser:

![image](https://user-images.githubusercontent.com/1116133/140270771-53c53957-6ce5-4488-9978-81fe7b367cfc.png)

All of this are requests of authorizations pending for allowing them in AWS, is there any way to not spawn a new browser tab if still open the latest?

**Comment by synfinatic** [comment]
No, because the URL's are different.  Each time you go through OIDC you get a new token and hence new URL which is time bound.  Hence the browser will always see it as a new URL and open a new tab.  At least, I don't know how to force any browser to not do that- it's definitely not cross-browser.

I suppose you could could use the `--url-action` option to only print the URL or copy to your clipboard so it never opens the browser directly.  That or if you (or your administrator) can increase the session timeout on either the IAM Permission Set/Role or SSO itself and avoid the need to refresh the IAM creds or SSO token.

**Comment by monwolf** [comment]
Make sense of your point, but printing the URL is not an option for my use case, because is embedded in another software to automatize the eks login with the sso and it didn't show the output, so  I will force me to close this software every day.

**Comment by synfinatic** [comment]
Correct.  This is the good/bad feature of SSO.  The STS credentials are temporary which makes them more secure.  AWS SSO CLI caches your SSO token so you don't have to re-authenticate via the browser every time, but once it does expire...

If your service/application needs to be running for more than a few hours without human intervention, you probably want to use static IAM user credentials or alternatively run it in AWS itself and let AWS manage passing the IAM creds to your service via something like EC2 Instance Role, etc.
