### ISSUE TITLE
feature: docs: document better the reason why `--open print` can't be used with process

### ISSUE THREAD

**Issue by kevcube** [synfinatic/aws-sso-cli#299]
**Is your feature request related to a problem? Please describe.**
I'm trying to use aws-sso within a docker container built on alpine, it doesn't have xclip, xsel, etc, and I would like to be able to use `--open print` to get URLs to my host machine. I don't really understand WHY that can't be done, but [this line](https://github.com/synfinatic/aws-sso-cli/blob/97eb23325f42d0d1e649a888b0d2727a6c7f0cc0/README.md?plain=1#L182) tells me that it can't.

**Describe the solution you'd like**
Better documentation around why this is impossible, maybe then we can request with AWS.

**Comment by synfinatic** [comment]
Basically what I'm saying here is that if you use `aws-sso process` inside of the `~/.aws/config` file with the `credential_process` feature, you can't use `--open print`.    This is because the execution of `aws-sso` happens via the AWS SDK and I can't print out the URL via stdout or stderr.

But there are other options:

```
eval $(aws-sso eval --open print ...)
<run one or more commands>
```

or:

`aws-sso exec --open print ... <one command here>`

**Comment by synfinatic** [comment]
oh, i didn't actually read your question/ticket well enough to answer correctly:

Basically, I don't think AWS can actually fix this issue.  The reason being is that `credential_process` reads from stdin and so the only option is stderr.  That isn't the end of the world, but since this is all happening via the AWS SDK, there is no guarantee that you the user can view stderr in the context of the execution.

I'm really kinda abusing the`credential_process` feature with AWS SSO because it really doesn't make sense to use it in an interactive manner (necessary for the SSO auth workflow), but since I have the ability to open the URL via a browser it kinda mostly works.

In the end, I don't have a legit solution to this issue to propose to AWS and hence I haven't opened a feature request with them.
