### ISSUE TITLE
No "clear" command, FATAL   Unable to continue   error="Conflicting environment variable 'AWS_ACCESS_KEY_ID' is set"

### ISSUE THREAD

**Issue by apimu** [synfinatic/aws-sso-cli#455]
**Output of `aws-sso version`:**
```
Example output:
AWS SSO CLI Version 1.9.6 -- Copyright 2021-2022 Aaron Turner
c3208fd25e1f57a77f3d3d9f2b48158ce5c4cef2 (Homebrew) built at 2022-12-22T15:27:18+0000
```

**Describe the bug:**
There is no "clear" command even tho the docs list it as such. Ive tried using flush as well, but i continue to get errors and cannot preform aws-sso exec. I will only receive this error: "FATAL   Unable to continue   error="Conflicting environment variable 'AWS_ACCESS_KEY_ID' is set"

**To Reproduce:**
 1. Leave terminal open until creds expire
 2. run aws-sso exec
 3. 
**Expected behavior:**
I expect to be able to switch accounts, or to be able to use the "aws-sso-clear" command according to the documentation.

**Screenshots:**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version Ventura 13.0.1

**Additional context:**

**Contents of `~/.aws-sso/config.yaml`:**
➜  ~ cat ~/.aws-sso/config.yaml
SSOConfig:
    DefaultSSO:
        SSORegion: us-east-1
        StartUrl: removedforprivacy
        DefaultRegion: us-east-1
DefaultRegion: us-east-1
ConsoleDuration: 60
CacheRefresh: 168
UrlAction: open
ConfigProfilesUrlAction: open
LogLevel: error
HistoryLimit: 10
HistoryMinutes: 1440
File contents go here...
```

**Comment by synfinatic** [comment]
Can you point to me where the docs show a `clear` command?  That way I can fix the docs since there is no such command.

Regarding your issue, this isn't a bug but rather "as-designed" and effectively a limit with how your shell (bash/zsh/etc) works.  The `aws-sso exec` command is executing your shell to create a new shell environment and passing in the necessary `AWS_` environment variables.

Hence to do a "clear" you would type `exit` to exit this new shell and return to your previous shell.

If you don't wish to be creating a new sub shell, then you need to use `eval $(aws-sso eval ...)` [as documented](https://github.com/synfinatic/aws-sso-cli/blob/main/docs/commands.md#eval).  Then you can use `eval $(aws-sso eval --clear)` to clear.

**Comment by apimu** [comment]
Im open to the idea I may be mistaken, but this is where Im getting the idea this is a "clear" command: 
<img width="965" alt="Screenshot 2022-12-22 at 08 21 49" src="https://user-images.githubusercontent.com/121245451/209178132-cbd088b7-32e3-45b4-91c1-0480e143cf2b.png">

**Comment by synfinatic** [comment]
Ah, `aws-sso-clear`.  Yes that is a shell helper.  Have you installed the shell completions via `aws-sso completions --install`?

**Comment by apimu** [comment]
No, I had not, thank you for the clarifications. I'm all set now Thank you.
