### ISSUE TITLE
[Feature request] Support for MFA

### ISSUE THREAD

**Issue by negoziator** [synfinatic/aws-sso-cli#90]
Feature request:

As far as I can see the package does not support SSO with MFA atm 😊

This is only a feature request, that makes the package support MFA 

Feel free to comment to start a discussion on the topic 👍🏼

Read on MFA here : https://docs.aws.amazon.com/singlesignon/latest/userguide/enable-mfa.html

**Comment by synfinatic** [comment]
Hi @negoziator !

So with AWS SSO, users authenticate through their SSO provider (typically OneLogin or Okta) and provide the MFA code on their website.  Hence, there is no need for AWS SSO CLI to "support" MFA, because it never needs to see your username, password or MFA token code.

Note, if you are familiar with the AWS SAML integration, then that has different authentication workflow, and yes supporting MFA would be necessary.  If you are using OneLogin, you may find [OneLogin AWS Assume Role](https://github.com/synfinatic/onelogin-aws-role) useful- although to be honest I'm not actively developing that anymore.

**Comment by negoziator** [comment]
Ah okay. Right 😁

Well I'm not an expert or anything obviously.

Thank you for clarifying 😎
